# Site settings
title: Tenghui Deng
email: dth16@tsinghua.org.cn
description: Personal webpage of Dr. Tenghui Deng 
baseurl: ""
url: "https://tenghui-deng.github.io"


# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Haibo Li<br/>
  Research Fellow <br/> 
  University of Melbourne 
  <!-- Associate Professor <br/>
  Huazhong University of Science and Technology -->

location: >
  G82, Peter Hall Building (160)<br/>
  University of Melbourne<br/>
  Melbourne VIC 3010, Australia


contact: >
  <a href="mailto:haibolee1729@gmail.com" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Haibo via email</a><br/>


# Pages shown in navbar
nav_pages:
  - name: about
  - name: research
  - name: publications
  # - name: talks
  - name: teaching
  # - name: team
  - name: blog

include:
  - .htaccess
  - _pages
  - robots.txt

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"  

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

# plugins: ["jekyll/scholar"]
plugins:
  - jekyll-scholar
  - jekyll-sitemap

# 允许运行本地自定义插件
future: true
safe: false
plugins_dir: _plugins
# 给“tex → posts”的插件一份最小配置
tex_posts:
  src_dir: posts_src         # 你放 .tex 的目录
  out_dir: _posts            # 输出到 _posts
  layout: post               # 生成文章用的 layout

scholar:
  last_name: Li
  first_name: [Haibo]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - posts_src
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
